# Generated by Django 6.1 on 2026-08-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_data', '0005_developeractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_analyzed', models.PositiveIntegerField(default=0)),
                ('lines_of_code', models.PositiveIntegerField(default=0)),
                ('functions', models.PositiveIntegerField(default=0)),
                ('classes', models.PositiveIntegerField(default=0)),
                ('imports', models.PositiveIntegerField(default=0)),
                ('complexity', models.PositiveIntegerField(default=0)),
                ('max_nesting', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_quality', to='github_data.repository')),
            ],
        ),
        migrations.CreateModel(
            name='CodeQualityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=50)),
                ('lines_of_code', models.PositiveIntegerField(default=0)),
                ('functions', models.PositiveIntegerField(default=0)),
                ('classes', models.PositiveIntegerField(default=0)),
                ('imports', models.PositiveIntegerField(default=0)),
                ('complexity', models.PositiveIntegerField(default=0)),
                ('max_nesting', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='analytics.codequalityanalysis')),
            ],
        ),
    ]
