# Generated by Django 6.1 on 2026-08-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='analyzed_at',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='files_analyzed',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='imports',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='lines_of_code',
        ),
        migrations.RemoveField(
            model_name='codequalityanalysis',
            name='max_nesting',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='imports',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='lines_of_code',
        ),
        migrations.RemoveField(
            model_name='codequalityfile',
            name='max_nesting',
        ),
    ]
