# Generated by Django 6.1 on 2026-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_codequalityanalysis_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codequalityanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='classes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='complexity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='files_analyzed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='functions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='high_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='imports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='languages',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='lines_of_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='low_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='max_nesting',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='medium_issues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityanalysis',
            name='quality_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='classes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='complexity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='file_path',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='functions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='imports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='language',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='lines_of_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codequalityfile',
            name='max_nesting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
