# Generated by Django 6.1 on 2026-08-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('committed_at', models.DateTimeField()),
                ('html_url', models.URLField(blank=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github_data.repository')),
            ],
        ),
    ]
