# Generated by Django 6.1 on 2026-08-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('github_data', '0004_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commits', models.PositiveIntegerField(default=0)),
                ('active_days', models.PositiveIntegerField(default=0)),
                ('total_pull_requests', models.PositiveIntegerField(default=0)),
                ('total_issues', models.PositiveIntegerField(default=0)),
                ('consistency_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='accounts.developerprofile')),
            ],
        ),
    ]
